### ISSUE TITLE
Restart dopo 24hh

### ISSUE THREAD

**Issue by maframan** [roncoa/SmartHome#1]
Ciao, 
grazie prima di tutto per l'ottimo lavoro.
Sto utilizzando la versione 4.5 e mi succede una cosa strana ossia dopo 24hh (minuto più, minuto meno) il nodemcu si riavvia e mi causa la chiusura della tapparella. Al momento mi viene da pensare che è il DHCP che rinegozia l'IP address e in questo caso ho visto che viene richiamato ESP.restart(). C'è modo di risolvere questo problema oppure mi diresti cosa fare?

Grazie mille
Francesco

**Comment by roncoa** [comment]
Ciao Francesco,
grazie per l'utilizzo di SmartHome e per il feedback.
Non è normale quello che ti accade. Dovrei vedere lo schema elettrico che
hai usato e il file SmartHome_config.h.
Comunque, se vuoi evitare che si resetti una volta al giorno, nello sketch
SmartHome_v45.ino, nel void loop (), togli o commenti la riga "
loop_reset_giornaliero();"

Non so se sei iscritto al gruppo di
Facebook: https://www.facebook.com/groups/351472505248816/

Inviato da LG

Il giorno mar 4 dic 2018, 20:51 maframan <notifications@github.com> ha
scritto:

**Comment by roncoa** [comment]
Ciao Francesco, 
grazie per l'utilizzo di SmartHome e per il feedback. 
Non è normale quello che ti accade. Dovrei vedere lo schema elettrico che hai usato e il file SmartHome_config.h. 
Comunque, se vuoi evitare che si resetti una volta al giorno, nello sketch SmartHome_v45.ino, nel void loop (), togli o commenti la riga "loop_reset_giornaliero();"

Non so se sei iscritto al gruppo di
Facebook: https://www.facebook.com/groups/351472505248816/

**Comment by benji51** [comment]
Succede anche a me con la versione v45. Una volta al giorno mi si chiude la serranda.  A me la cosa andrebbe pure bene se riuscissi a stabilire io l'orario. Appena riesco provo 
il tuo suggerimento. Per il resto è la migliore App che ho trovato in circolazione.

**Comment by roncoa** [comment]
È un bug noto della v4.5.
Si presenta se non hai connesso nessun GPIO ai bottoni SU GIU.
Al riavvio, il firmware pensa che il bottone (non trovandolo) è ststo rilasciato. 
Nella versione 50 beta3 è stato risolto. 
Se hai bisogno di mantenere la v4.5 dimmelo che li fixo anche in quella. 
Grazie del feedback.

**Comment by roncoa** [comment]
Ti ho risposto su github. 👍🏻


Inviato da LG

Il giorno mer 19 dic 2018, 06:14 benji51 <notifications@github.com> ha
scritto:

**Comment by benji51** [comment]
Si, grazie, se non ti crea troppo lavoro. Volevo mantenere il v4.5 per l'ufficio
