### ISSUE TITLE
Versione ethernet

### ISSUE THREAD

**Issue by sarz4fun** [roncoa/SmartHome#2]
Ciao Roncoa. Ho visto il tuo progetto e mi sembra molto bello.
Volevo chiedere se avevi in programma la possibilità di usare la ethernet shield w5100 al posto della esp8266. In questo modo tutto sarebbe gestibile via cavo al posto che wifi, con vantaggi in affidabilità.
Grazie.
 Ciao.

**Comment by roncoa** [comment]
Per ora non è in programma.
Magari più avanti includerò Arduino + ethernet shield.

Ciao

Inviato da LG

Il giorno sab 5 gen 2019, 11:52 sarz4fun <notifications@github.com> ha
scritto:
