### ISSUE TITLE
controllo veneziane motorizzate

### ISSUE THREAD

**Issue by megamarco833** [roncoa/SmartHome#3]
Ciao, complimenti per il lavoro!!!
mi chiedevo se si potesse aggiungere il controllo veneziana, praticamente una tapparella ma con la possibilità di orientare UP o down gli oscuranti.
praticamente si avrebbe il motore comandato da due relay come la tapparella, uno per up ed uno per down
si avrebbero 2 pulsanti a muro: 1 per up ed uno per down

il problema è che il funzionamento sarebbe il seguente:
quando si preme il pulsante di UP attiva per "x" secondi (x=numero di secondi o frazione di secondo impostabile)  il relay UP e gli oscuranti si inclinano in direzione UP
se si ripreme nuovamente il pulsante UP , si deve attivare ancora il gpio del motore Up per "x" secondi e gli oscuranti si inclineranno ancora in direzione UP

se viene premuto il pulsante UP per più di 2 secondi (impostabili) allora viene attivato il relay UP in modo continuo per il totale di secondi impostati, cioè fino a che l'oscurante si alza completamente.

stessa identica cosa per il Down.

grazie!

p.s io uso domoticz, sarebbe bello potesse integrarsi anche con domoticz, magari avendo un campo da compilare in cui si inserisce l'idx del device corrispondente in domoticz

**Comment by roncoa** [comment]
Ciao Marco, grazie per l'interessamento.
Per il momento purtroppo non avendo nessuna veneziana da poter provare, non ho in programma di implementare la cosa.
Per quanto riguarda domoticz, non lo conosco, io uso Home Assistant. La cosa pero' potrebbe essere interessante e potrei pensare di implementarla.
Avresti da consigliarmi una guida o documentazione su come poter implementare in domoticz dispositivi che comunicano con MQTT?
Grazie.

**Comment by megamarco833** [comment]
ciao, figurati, i complimenti sono meritatissimi!
per le veneziane, peccato, ormai le tapparelle (semplice su e giù) stanno pian piano sparendo nelle nuove realizzazioni e ristrutturazioni e stanno prendendo sempre più piede gli oscuranti che sono molto più versatili, con pareti mobili.
alcuni firmware per domotica si stanno infatti muovendo in quella direzione, per questo ti chiedevo se lo volessi implementare :)
io li ho, se vuoi ti posso allegare un video sul funzionamento, se mai deciderai di implementarlo, ovvio.
tra l'altro l'idea della temporizzazione del relay in "shortpress" o "longpress" è solo un modo semplicistico di affrontare il problema, l'ideale sarebbe quello di utlizzare una variabile per memorizzare il movimento e così avere un controllo molto più preciso :)

per domoticz certo, esiste la wiki:
https://www.domoticz.com/wiki/MQTT
è un sistema molto semplice, ed io mi sono spostato da home Assistant a domoticz, che è un poco meno supportato, ma ha molte potenzialità in più poichè prevede l'utilizo di dzvents, un linguaggio basato su lua, ma molto più intuitivo e semplice, che essendo un linguaggio vero e proprio di programmazione permette di automatizzare e realizzare qualsiasi combinazione senza limiti.
Per quanto mi riguarda, un sistema domotico, serve appunto a realizzare cose complesse, cosa che con home assistant non riuscivo a gestire, o rendeva molto cervellotica l'implementazione, con un linguaggio di programmazione (come dzvents ad esempio) invece fai quello che vuoi :)
quindi per concludere vedo home assistant ottimo per le cose "di ruotine" o semplici/tradizionali e per l'ottimo supporto, mentre domoticz, è fenomenale se uno si vuole spingere un po' più in la, ma richiede un impeno un po' maggiore.

se ti andasse di estendere l'automazione anche a domoticz, estenderesti di molto la versatilità del tuo firmware.
per l'interfaccia nel firmware dovresti aggiungere un campo da compilare in cui inserire l'IDX (univovo per ogni dispositivo di domoticz) e poi il firmware dovrebbe fare "il lavoro sporco" di mandare i comandi mqtt al topic `domotiz/in` ed ascoltare i comandi che manda domoticz dal topic `domoticz/out`
ad esempio il firmware tasmota, implementa nativamente l'integrazione a domoticz in questo modo.
