### ISSUE TITLE
LongClick per Temporizzatori

### ISSUE THREAD

**Issue by El-Carvin** [roncoa/SmartHome#4]
Ciao e complimenti per il tuo firmware, eccellente per la semplicità di utilizzazione e per completezza.
Volendo utilizzare un NodeMcu per gestire alcuni (3) temporizzatori che gestiscono le luci di un corridoio e di un garage, attivati da sensori PIR e controllati anche da remoto. Come sai i sensori PIR, una volta percepita una presenza nella zona controllata, hanno l'uscita attivata per ben più di due secondi, e quindi i temporizzatori si resettano.
Mi chiedevo se fosse possibile disattivare la funzione LongClick e, se si come.

Grazie ancora per il tuo lavoro e per il tempo che vorrai dedicarmi.

**Comment by roncoa** [comment]
Ciao e grazie per l'interessamento a SmartHome.
Ho già predisposto la prossima release per avere la scelta in fase di configurazione se abilitare o meno il longclick. 
Funzionerà così : 
longclick NON abilitato (funzionamento normale)
     click accende e fa partire il timer
     (successivi click lasciano acceso e fanno ripartire il timer)
     nel caso click>timer, il rele' si spegne dopo il rilascio del bottone. 
longclick abilitato:
     click accende e fa partire il timer
     (successivi click lasciano acceso e fanno ripartire il timer)
     longclick (1.5 secondi) spegne
     longlongclick (>3 secondi) accende fisso senza timer
In pratica con il long click abilitato si puo' sia spegnere il temporizzatore che lasciarlo acceso fisso. 
Per spegnerlo basta un long click di 1.5 secondi.
Per accenderlo fisso un long click di 3 secondi. In questo caso vedremo il rele' accendersi, spegnersi per un attimo e riaccendersi fisso. (cosi' chi preme il pulsante ha una sorta di segnalazione di rele' fisso).
Da rele' acceso visso, basta un click per far ripartire il timer e un longclick (1.5 secondi) per farlo spegnere.

**Comment by El-Carvin** [comment]
Ciao, grazie e complimenti ancora
Ero quasi certo di una possibile evoluzione della funzione LongClick, e me l'hai confermato.

Attendo la prossima release.

Grazie ancora

**Comment by El-Carvin** [comment]
Buongiorno,
continuando a testare il firmware ho notato che sul nodo tapparella il tempo massimo impostato viene modificato automaticamente, riducendolo, qualora ci sia l'intervento dei fine-corsa prima dell'azzeramento del T.max stesso.
Generalmente, per l'uso con le tapparelle elettriche è corretto, anche se normalmente i motori delle tapparelle hanno a bordo i loro fine-corsa.
Per poter utilizzare i nodi tapparella in altre applicazioni, per esempio per gestire scale retrattili automatizzate (come nel caso che sto testando io) la modificazione del T.max può diventare un limite che sarebbe meglio non avere. Lasciare invariato il T.max diventerebbe una sicurezza in più per un eventuale mancato intervento proprio dei fine corsa.
Ti domando se anche questa funzione potrà essere implementata nella prossima release.

Grazie ancora per il tuo lavoro e per l'attenzione che mi vorrai riservare

**Comment by roncoa** [comment]
Ciao,
se non utilizzi i finecorsa di SmartHome, il tmax non viene modificato.

**Comment by El-Carvin** [comment]
Ciao
...per un utilizzazione con le tapparelle elettriche è corretto non utilizzare i fine-corsa di SmartHome, ma l'uso dei FC del nodo tapparelle di SH per funzioni alternative  (come per l'esempio che ti facevo prima, scala retrattile) è quanto meno indispensabile, in quanto questi FC vengono attivati anche da sensori che rilevano eventuali ostacoli estemporanei/accidentali che si possano frapporre al movimento. 
La mia voleva essere solo una osservazione su come rendere questo già ottimo FW ancora più versatile.
Grazie
