### ISSUE TITLE
Codice open source?

### ISSUE THREAD

**Issue by fabianoriccardi** [roncoa/SmartHome#5]
Ciao,
grazie per l'interessante lavoro! Volevo chiederti se il progetto fosse open source. Nel caso mi potresti indicare dove posso trovare il codice?

**Comment by roncoa** [comment]
Il progetto è nato open source, infatti fino alla versione 5.0 ho distribuito i sorgenti.
Dopo aver visto che parti del mio codice erano presenti in altri firmware a mia insaputa e soprattutto senza una citazione a SmartHome, ho deciso che per il momento la versione 6.0 verrà distribuita solo già compilata.

**Comment by fabianoriccardi** [comment]
Capisco, grazie per la risposta.
