### ISSUE TITLE
Problema con caratteri password WiFi

### ISSUE THREAD

**Issue by Roger4Code** [roncoa/SmartHome#7]
Ciao! ho notato che se inserisco una password del WiFi con la "&" questa non viene interpretata correttamente (viene ignorato il resto della password dal & in poi).
E' complesso applicare una fix per questo?

thx!!!

TC

**Comment by roncoa** [comment]
Ciao, che versione stai usando?
Quel bug dovrebbe essere stato risolto dalla v7.0 beta 6 in poi.

**Comment by Roger4Code** [comment]
Ciao!
ho preso l'ultima release che ho trovato, e ho seguito la guida su domhouse:
==> Release SmartHome_v71beta4_1M.bin

Dai messaggi del debug e' chiaro tronca la password, nella sezione iniziale
di quando fa il boot, stampa la password troncata.

grazie mille!

TC

Il giorno dom 14 nov 2021 alle ore 22:19 Roncoa ***@***.***>
ha scritto:

**Comment by roncoa** [comment]
Allora ricontrollo 👍🏻

**Comment by Roger4Code** [comment]
Top! Grazie mille!!!

Complimenti per il progetto, veramente versatile e tutto ben documentato!

**Comment by roncoa** [comment]
Ho aggiornato il firmware e sostituito i files della v71beta4 , riscaricali.
Non avendo caratteri speciali nei campi ssid o password non ho potuto provare.
Se riesci, fammi sapere se ora è ok, grazie.

**Comment by Roger4Code** [comment]
Ok, grazie mille!

Domani metto su la nuova release e ti do un feedback.

Thx!

**Comment by Roger4Code** [comment]
Ciao!
problema rientrato, thx!!!

TC

Il giorno mar 16 nov 2021 alle ore 20:00 Roncoa ***@***.***>
ha scritto:
