### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gitlaman** [roncoa/SmartHome#8]

**Comment by roncoa** [comment]
Hi gitlaman,
thank you for using SmartHome.
As for the R503 Fingerprint module, SmartHome does not set any passwords by itself.
The only way to set a password is to do it manually by sending the Payload "FP_password=pwd" (where pwd is your password) to the node Topic.
In this case, you can reset the password by sending the Payload "FP_reset_password" to the Topic of the node.
If you have not used this command, SmartHome cannot change the password by itself.

As for the boot time, it is influenced by Home Assistant's Discovery routine. In new releases I reduced it.

Greetings

**Comment by gitlaman** [comment]
Thanks for the answer, i found out just now that the problem is not the password but something with my espHome setup because i saw that i can communicate when im sending the cancel commands. Sorry that i cleared the comments, i thought that you didnt saw so not to bother you :).

Anyway thanks again and have a nice day
